# Generated by Django 6.0.7 on 2026-07-27 15:22

import django.db.models.deletion
import galleries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Ako je prazno, koristi se glavni naslov. Google obično prikazuje do 60 znakova.', max_length=70)),
                ('meta_title_hr', models.CharField(blank=True, help_text='Ako je prazno, koristi se glavni naslov. Google obično prikazuje do 60 znakova.', max_length=70, null=True)),
                ('meta_title_en', models.CharField(blank=True, help_text='Ako je prazno, koristi se glavni naslov. Google obično prikazuje do 60 znakova.', max_length=70, null=True)),
                ('meta_description', models.CharField(blank=True, help_text='Kratki opis za Google rezultate pretrage. Do 160 znakova.', max_length=160)),
                ('meta_description_hr', models.CharField(blank=True, help_text='Kratki opis za Google rezultate pretrage. Do 160 znakova.', max_length=160, null=True)),
                ('meta_description_en', models.CharField(blank=True, help_text='Kratki opis za Google rezultate pretrage. Do 160 znakova.', max_length=160, null=True)),
                ('title', models.CharField(max_length=200)),
                ('title_hr', models.CharField(max_length=200, null=True)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(max_length=220)),
                ('slug_hr', models.SlugField(max_length=220, null=True)),
                ('slug_en', models.SlugField(max_length=220, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_hr', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Manji broj = prikazuje se prije na početnoj stranici.')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Galleries',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=galleries.models.gallery_image_upload_path)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('alt_text_hr', models.CharField(blank=True, max_length=200, null=True)),
                ('alt_text_en', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='galleries.gallery')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
