# Generated by Django 6.0.7 on 2026-08-27 16:07

import common.validators
import sitesettings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=sitesettings.models.hero_image_upload_path, validators=[common.validators.validate_image_size])),
                ('alt_text_hr', models.CharField(blank=True, max_length=200)),
                ('alt_text_en', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
    ]
