# Generated by Django 6.0.7 on 2026-07-27 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Ako je prazno, koristi se glavni naslov. Google obično prikazuje do 60 znakova.', max_length=70)),
                ('meta_title_hr', models.CharField(blank=True, help_text='Ako je prazno, koristi se glavni naslov. Google obično prikazuje do 60 znakova.', max_length=70, null=True)),
                ('meta_title_en', models.CharField(blank=True, help_text='Ako je prazno, koristi se glavni naslov. Google obično prikazuje do 60 znakova.', max_length=70, null=True)),
                ('meta_description', models.CharField(blank=True, help_text='Kratki opis za Google rezultate pretrage. Do 160 znakova.', max_length=160)),
                ('meta_description_hr', models.CharField(blank=True, help_text='Kratki opis za Google rezultate pretrage. Do 160 znakova.', max_length=160, null=True)),
                ('meta_description_en', models.CharField(blank=True, help_text='Kratki opis za Google rezultate pretrage. Do 160 znakova.', max_length=160, null=True)),
                ('title', models.CharField(max_length=200)),
                ('title_hr', models.CharField(max_length=200, null=True)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(max_length=220)),
                ('slug_hr', models.SlugField(max_length=220, null=True)),
                ('slug_en', models.SlugField(max_length=220, null=True)),
                ('content', models.TextField()),
                ('content_hr', models.TextField(null=True)),
                ('content_en', models.TextField(null=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
